# Generated by Django 4.1.3 on 2022-11-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
